server:
  address: localhost

management:
  context-path: /admin

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadataMap:
      instanceId: ${spring.application.name}
      management:
        context-path: ${management.context.path}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
