version: '3.5'

services:
  postgres:
    image:  "postgres:alpine"
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: rainbow_database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - rainbow_database: /database
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - auth-network
    
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports: 
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_USER: dbadmin
      DB_PASSWORD: dbpass
      DB_DATABASE: rainbow_database
      DB_SCHEMA: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8081/auth
    restart: always
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge  
    
volumes:
    rainbow_database: 